apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pacmanpvc100

resources:
- ../../base
#- mongo-pvc-100G.yaml
#
#nameSuffix: pvc100

patches:
- path: pvc-patch.yaml
  target:
    kind: PersistentVolumeClaim
    name: mongo-storage
